# frozen_string_literal: true

task "bundle" do
  require "fileutils"

  files = %w[main.rb utils.rb Gemfile]

  contents =
    files.to_h do |file|
      [file, File.read(file).split("# frozen_string_literal: true\n").last]
    end

  vim_imagegen = +<<~VIM_IMAGEGEN
  #!/usr/bin/env ruby
  # frozen_string_literal: true
  # This file was generated by Rakefile.
  require "bundler/inline"
  VIM_IMAGEGEN
  vim_imagegen << "gemfile do\n"
  vim_imagegen << contents["Gemfile"]
  vim_imagegen << "end\n"
  vim_imagegen << contents["main.rb"].sub(
    "require_relative \"utils\"",
    contents["utils.rb"]
  )

  File.write("vim-imagegen", vim_imagegen)
  FileUtils.chmod("+x", "vim-imagegen")
  puts "Generated vim-imagegen"
end
